# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

content:
  resource: "@AlomWebsiteBundle/Resources/config/routing.xml"

blog:
  resource: "@AlomWebsiteBundle/Resources/config/routing.xml"

_imagine:
  resource: .
  type:     imagine

